download_root = "<your download root>"
concurrency = 4
max_rps = 2
user_agent = ""
course_include = ["*"]
course_exclude = []
week_pattern = ""

[naming]
safe_fs = true

[logging]
level = "info"
file = "<your log file>"

[canvas]
base_url = "<https://canvas.yourinstitution.domain>"
token = "<your token>"
ignored_courses = [""] # courses to ignore
token_cmd = ""
cookie_file = "~/.config/u_crawler/canvas_cookies.txt"  # Netscape export from Canvas session
sso_email = "<your email>"
sso_password = "<your password>"

[zoom]
enabled = true
ffmpeg_path = "ffmpeg"  # or full path if not on $PATH
cookie_file = "~/.config/u_crawler/zoom_cookies.txt"    # Netscape export from Zoom session
user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36 Edg/140.0.0.0"
external_tool_id = 187
